name: Update WAProto

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-proto:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Root Dependencies
        run: yarn install

      - name: Install proto-extract Dependencies
        run: npm install --prefix proto-extract

      - name: Update WAProto.proto
        id: wa_proto_info
        run: |
          cd proto-extract
          node index.js > ../wa-logs.txt
          cd ..
          cat wa-logs.txt
          WA_VERSION=$(grep "Current version:" wa-logs.txt | awk '{print $NF}')
          WA_REVISION=$(echo $WA_VERSION | awk -F. '{print $NF}')
          WA_JS_URL=$(grep "Found source JS URL:" wa-logs.txt | awk '{print $NF}')
          echo "wa_version=$WA_VERSION" >> $GITHUB_OUTPUT
          echo "wa_revision=$WA_REVISION" >> $GITHUB_OUTPUT
          echo "wa_js_url=$WA_JS_URL" >> $GITHUB_OUTPUT
          echo "Detected Version: $WA_VERSION"
          echo "Detected Revision: $WA_REVISION"

      - name: Generate Protobuf Statics
        run: yarn gen:protobuf

      - name: Update Yebails Version Files
        run: node scripts/update-wa-version.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: updated proto and version to v${{ steps.wa_proto_info.outputs.wa_version }}'
          title: 'WhatsApp v${{ steps.wa_proto_info.outputs.wa_version }} Proto Update'
          branch: 'automation/update-proto'
          base: 'main'
          delete-branch: true
          labels: 'automation, update-proto'
          body: |
            ## Automated WhatsApp Proto Update
            This PR updates the `WAProto.proto` file and the WhatsApp Web version in the library.
            - **WA Version**: `${{ steps.wa_proto_info.outputs.wa_version }}`
            - **Revision**: `${{ steps.wa_proto_info.outputs.wa_revision }}`
            
            This update was automatically generated by the `update-proto` workflow.
          add-paths: |
            WAProto/*
            lib/Defaults/yebails-version.json
            lib/Defaults/index.js
