name: Update WAProto

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-proto:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Root Dependencies
        run: yarn install

      - name: Install proto-extract Dependencies
        run: npm install --prefix proto-extract

      - name: Update WAProto.proto
        id: wa_proto_info
        run: |
          cd proto-extract
          node index.js > ../wa-logs.txt
          cd ..
          cat wa-logs.txt
          WA_VERSION=$(grep "Current version:" wa-logs.txt | awk '{print $NF}')
          WA_REVISION=$(echo $WA_VERSION | awk -F. '{print $NF}')
          WA_JS_URL=$(grep "Found source JS URL:" wa-logs.txt | awk '{print $NF}')
          echo "wa_version=$WA_VERSION" >> $GITHUB_OUTPUT
          echo "wa_revision=$WA_REVISION" >> $GITHUB_OUTPUT
          echo "wa_js_url=$WA_JS_URL" >> $GITHUB_OUTPUT
          echo "Detected Version: $WA_VERSION"
          echo "Detected Revision: $WA_REVISION"

      - name: Generate Protobuf Statics
        run: yarn gen:protobuf

      - name: Update Yebails Version Files
        run: node scripts/update-wa-version.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add WAProto/* lib/Defaults/yebails-version.json lib/Defaults/index.js
          if git diff --staged --quiet; then
            echo "No changes detected, skipping push."
          else
            git commit -m "chore: automated update to WhatsApp v${{ steps.wa_proto_info.outputs.wa_version }}"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
